//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GlobalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GlobalResources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Us.
        /// </summary>
        public static string AboutUs {
            get {
                return ResourceManager.GetString("AboutUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        public static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACS.
        /// </summary>
        public static string ACS {
            get {
                return ResourceManager.GetString("ACS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administration.
        /// </summary>
        public static string Admin {
            get {
                return ResourceManager.GetString("Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age.
        /// </summary>
        public static string Age {
            get {
                return ResourceManager.GetString("Age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be between 1 and 130.
        /// </summary>
        public static string AgeRange {
            get {
                return ResourceManager.GetString("AgeRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age is required.
        /// </summary>
        public static string AgeRequired {
            get {
                return ResourceManager.GetString("AgeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I Agree.
        /// </summary>
        public static string AgreePrivacyPolicy {
            get {
                return ResourceManager.GetString("AgreePrivacyPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please create profile before moving to other steps.
        /// </summary>
        public static string AlertCreateProfileFirst {
            get {
                return ResourceManager.GetString("AlertCreateProfileFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The web site is experiencing a problem, please try again or later.
        /// </summary>
        public static string AlertSystemIssue {
            get {
                return ResourceManager.GetString("AlertSystemIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anderson Cancer Center.
        /// </summary>
        public static string AndersonCancerCenter {
            get {
                return ResourceManager.GetString("AndersonCancerCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ASCO.
        /// </summary>
        public static string ASCO {
            get {
                return ResourceManager.GetString("ASCO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Best Treatment Report.
        /// </summary>
        public static string BestTreatmentReport {
            get {
                return ResourceManager.GetString("BestTreatmentReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Better Doctor Needs Better Information.
        /// </summary>
        public static string BetterDoctorBetterInformation {
            get {
                return ResourceManager.GetString("BetterDoctorBetterInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beyond physical treatment.
        /// </summary>
        public static string BeyondPhysicalTreatment {
            get {
                return ResourceManager.GetString("BeyondPhysicalTreatment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boost patient&apos;s overal health?.
        /// </summary>
        public static string BoostPatientHealth {
            get {
                return ResourceManager.GetString("BoostPatientHealth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Breast Cancer.
        /// </summary>
        public static string BreastCancer {
            get {
                return ResourceManager.GetString("BreastCancer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancer 101.
        /// </summary>
        public static string Cancer101 {
            get {
                return ResourceManager.GetString("Cancer101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancer Diagnosis.
        /// </summary>
        public static string CancerDiagnosis {
            get {
                return ResourceManager.GetString("CancerDiagnosis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancer Education.
        /// </summary>
        public static string CancerEducation {
            get {
                return ResourceManager.GetString("CancerEducation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancer Institutes.
        /// </summary>
        public static string CancerInstitutes {
            get {
                return ResourceManager.GetString("CancerInstitutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancer Risk Analysis.
        /// </summary>
        public static string CancerRiskAnalysis {
            get {
                return ResourceManager.GetString("CancerRiskAnalysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancer Stage Guide.
        /// </summary>
        public static string CancerStageGuide {
            get {
                return ResourceManager.GetString("CancerStageGuide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancer type is required.
        /// </summary>
        public static string CancerTypeRequired {
            get {
                return ResourceManager.GetString("CancerTypeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Symptom.
        /// </summary>
        public static string CheckSymptom {
            get {
                return ResourceManager.GetString("CheckSymptom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chemotherapy Agent Search.
        /// </summary>
        public static string ChemotherapyAgentSearch {
            get {
                return ResourceManager.GetString("ChemotherapyAgentSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ChemotherapyLog.
        /// </summary>
        public static string ChemotherapyLog {
            get {
                return ResourceManager.GetString("ChemotherapyLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Your Language.
        /// </summary>
        public static string ChooseYourLanguage {
            get {
                return ResourceManager.GetString("ChooseYourLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clinical Trail.
        /// </summary>
        public static string ClinicalTrail {
            get {
                return ResourceManager.GetString("ClinicalTrail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clinical Trail Report.
        /// </summary>
        public static string ClinicalTrailReport {
            get {
                return ResourceManager.GetString("ClinicalTrailReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find clinical trails in patient&apos;s interested location. The experimental treatment may be helpful if current treatment cannot stop cancer from growing or patient exhausted all effective treatment options..
        /// </summary>
        public static string ClinicalTrailReportLegend {
            get {
                return ResourceManager.GetString("ClinicalTrailReportLegend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colon Cancer.
        /// </summary>
        public static string ColonCancer {
            get {
                return ResourceManager.GetString("ColonCancer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common Q &amp; A.
        /// </summary>
        public static string CommonQA {
            get {
                return ResourceManager.GetString("CommonQA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Communication Platform.
        /// </summary>
        public static string CommunicationPlatform {
            get {
                return ResourceManager.GetString("CommunicationPlatform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evidence-Based Medical Information Research &amp; Spread (USA).
        /// </summary>
        public static string CompanyName {
            get {
                return ResourceManager.GetString("CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compare Diseases.
        /// </summary>
        public static string CompareDiseases {
            get {
                return ResourceManager.GetString("CompareDiseases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consult Treatment In USA.
        /// </summary>
        public static string ConsultTreatmentInUSA {
            get {
                return ResourceManager.GetString("ConsultTreatmentInUSA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Us.
        /// </summary>
        public static string ContactUs {
            get {
                return ResourceManager.GetString("ContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cretae Patient Profile.
        /// </summary>
        public static string CreatePatientProfile {
            get {
                return ResourceManager.GetString("CreatePatientProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagnosis &amp; Treatment Consulting.
        /// </summary>
        public static string DiagnosisAndTreatmentConsulting {
            get {
                return ResourceManager.GetString("DiagnosisAndTreatmentConsulting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide the month and year the diagnosis was made.
        /// </summary>
        public static string DiagnosisDateRequired {
            get {
                return ResourceManager.GetString("DiagnosisDateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disease 101.
        /// </summary>
        public static string Disease101 {
            get {
                return ResourceManager.GetString("Disease101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disease ID is required.
        /// </summary>
        public static string DiseaseIDRequired {
            get {
                return ResourceManager.GetString("DiseaseIDRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose  a disease from the list.
        /// </summary>
        public static string DiseaseMustBeSelected {
            get {
                return ResourceManager.GetString("DiseaseMustBeSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disease name is required.
        /// </summary>
        public static string DiseaseNameRequired {
            get {
                return ResourceManager.GetString("DiseaseNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diseases.
        /// </summary>
        public static string Diseases {
            get {
                return ResourceManager.GetString("Diseases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Best clinical decisions depends on the best research evidence, integrated with physician’s clinical expertise and patient value..
        /// </summary>
        public static string EBM_Statement_1 {
            get {
                return ResourceManager.GetString("EBM_Statement_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editing Board.
        /// </summary>
        public static string EditingBoard {
            get {
                return ResourceManager.GetString("EditingBoard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter.
        /// </summary>
        public static string Enter {
            get {
                return ResourceManager.GetString("Enter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select an ethnic group.
        /// </summary>
        public static string EthnicGroupRequired {
            get {
                return ResourceManager.GetString("EthnicGroupRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evidence Based Cancer Treatment.
        /// </summary>
        public static string EvidenceBasedCancerTreatment {
            get {
                return ResourceManager.GetString("EvidenceBasedCancerTreatment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evidence Based Medicine (EBM).
        /// </summary>
        public static string EvidenceBasedMedicine {
            get {
                return ResourceManager.GetString("EvidenceBasedMedicine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exchange Experience.
        /// </summary>
        public static string ExchangeExperience {
            get {
                return ResourceManager.GetString("ExchangeExperience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What to expect during office visit?.
        /// </summary>
        public static string ExpectationForOfficeVisit {
            get {
                return ResourceManager.GetString("ExpectationForOfficeVisit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domestic and USA Expert Consulting.
        /// </summary>
        public static string ExpertConsulting {
            get {
                return ResourceManager.GetString("ExpertConsulting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expert Second Opinion.
        /// </summary>
        public static string ExpertSecondOpinion {
            get {
                return ResourceManager.GetString("ExpertSecondOpinion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explanation.
        /// </summary>
        public static string Explanation {
            get {
                return ResourceManager.GetString("Explanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Walk you through the diagnosis and treatment processes. Help you make informed treatment decision!.
        /// </summary>
        public static string FeatureMessage {
            get {
                return ResourceManager.GetString("FeatureMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback.
        /// </summary>
        public static string Feedback {
            get {
                return ResourceManager.GetString("Feedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find Drug Interactions.
        /// </summary>
        public static string FindDrugInteractions {
            get {
                return ResourceManager.GetString("FindDrugInteractions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What to do if no treatment seemingly working?.
        /// </summary>
        public static string FindNewTreatments {
            get {
                return ResourceManager.GetString("FindNewTreatments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find and compare standard treatment options.
        /// </summary>
        public static string FindStandardTreatments {
            get {
                return ResourceManager.GetString("FindStandardTreatments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stomach Cancer.
        /// </summary>
        public static string GastricCancer {
            get {
                return ResourceManager.GetString("GastricCancer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        public static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        public static string GenderFemale {
            get {
                return ResourceManager.GetString("GenderFemale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        public static string GenderMale {
            get {
                return ResourceManager.GetString("GenderMale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender is required.
        /// </summary>
        public static string GenderRequired {
            get {
                return ResourceManager.GetString("GenderRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate Report for Doctor.
        /// </summary>
        public static string GenerateReportForDoctor {
            get {
                return ResourceManager.GetString("GenerateReportForDoctor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go.
        /// </summary>
        public static string Go {
            get {
                return ResourceManager.GetString("Go", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Handle toxic or side effects.
        /// </summary>
        public static string HandleToxicEffects {
            get {
                return ResourceManager.GetString("HandleToxicEffects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Health Facts.
        /// </summary>
        public static string HealthFacts {
            get {
                return ResourceManager.GetString("HealthFacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Health Topics.
        /// </summary>
        public static string HealthTopics {
            get {
                return ResourceManager.GetString("HealthTopics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liver Cancer.
        /// </summary>
        public static string HepaticCancer {
            get {
                return ResourceManager.GetString("HepaticCancer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hot Topics.
        /// </summary>
        public static string HotTopics {
            get {
                return ResourceManager.GetString("HotTopics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How Can Evidence Based Medicine Help Me?.
        /// </summary>
        public static string HowEBMHelpMe {
            get {
                return ResourceManager.GetString("HowEBMHelpMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to Find Reliable Medical Information?.
        /// </summary>
        public static string HowToFindReliableInformationLeged {
            get {
                return ResourceManager.GetString("HowToFindReliableInformationLeged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information Services.
        /// </summary>
        public static string InformationServices {
            get {
                return ResourceManager.GetString("InformationServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is the teatment working?.
        /// </summary>
        public static string IsTreatmentWorking {
            get {
                return ResourceManager.GetString("IsTreatmentWorking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Japan Associatein for Oncology.
        /// </summary>
        public static string JapanAssociateinForOncology {
            get {
                return ResourceManager.GetString("JapanAssociateinForOncology", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Msut be less than 50 characters.
        /// </summary>
        public static string LastNameLong {
            get {
                return ResourceManager.GetString("LastNameLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name is required.
        /// </summary>
        public static string LastNameRequired {
            get {
                return ResourceManager.GetString("LastNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Live with Cancer.
        /// </summary>
        public static string LiveWithCancer {
            get {
                return ResourceManager.GetString("LiveWithCancer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Medical Spendings.
        /// </summary>
        public static string LogMedicalSpendings {
            get {
                return ResourceManager.GetString("LogMedicalSpendings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Off.
        /// </summary>
        public static string LogOff {
            get {
                return ResourceManager.GetString("LogOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log On.
        /// </summary>
        public static string LogOn {
            get {
                return ResourceManager.GetString("LogOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maintain treatment effects.
        /// </summary>
        public static string MaintainTreatmentEffects {
            get {
                return ResourceManager.GetString("MaintainTreatmentEffects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make informed decision - put all together.
        /// </summary>
        public static string MakeInformedDecision {
            get {
                return ResourceManager.GetString("MakeInformedDecision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make Treatment Plan.
        /// </summary>
        public static string MakeTreatmentPlan {
            get {
                return ResourceManager.GetString("MakeTreatmentPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medical authorities in USA.
        /// </summary>
        public static string MedicalAuthoritiesInUSA {
            get {
                return ResourceManager.GetString("MedicalAuthoritiesInUSA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medical Consulting Service.
        /// </summary>
        public static string MedicalConsultingService {
            get {
                return ResourceManager.GetString("MedicalConsultingService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medical Term Explanation.
        /// </summary>
        public static string MedicalTermExplanation {
            get {
                return ResourceManager.GetString("MedicalTermExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medical Terms.
        /// </summary>
        public static string MedicalTerms {
            get {
                return ResourceManager.GetString("MedicalTerms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medicines.
        /// </summary>
        public static string Medicines {
            get {
                return ResourceManager.GetString("Medicines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apr.
        /// </summary>
        public static string MonthPickerApr {
            get {
                return ResourceManager.GetString("MonthPickerApr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aug.
        /// </summary>
        public static string MonthPickerAug {
            get {
                return ResourceManager.GetString("MonthPickerAug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dec.
        /// </summary>
        public static string MonthPickerDec {
            get {
                return ResourceManager.GetString("MonthPickerDec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feb.
        /// </summary>
        public static string MonthPickerFeb {
            get {
                return ResourceManager.GetString("MonthPickerFeb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jan.
        /// </summary>
        public static string MonthPickerJan {
            get {
                return ResourceManager.GetString("MonthPickerJan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jul.
        /// </summary>
        public static string MonthPickerJul {
            get {
                return ResourceManager.GetString("MonthPickerJul", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jun.
        /// </summary>
        public static string MonthPickerJun {
            get {
                return ResourceManager.GetString("MonthPickerJun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mar.
        /// </summary>
        public static string MonthPickerMar {
            get {
                return ResourceManager.GetString("MonthPickerMar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to May.
        /// </summary>
        public static string MonthPickerMay {
            get {
                return ResourceManager.GetString("MonthPickerMay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Noc.
        /// </summary>
        public static string MonthPickerNov {
            get {
                return ResourceManager.GetString("MonthPickerNov", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oct.
        /// </summary>
        public static string MonthPickerOct {
            get {
                return ResourceManager.GetString("MonthPickerOct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sep.
        /// </summary>
        public static string MonthPickerSep {
            get {
                return ResourceManager.GetString("MonthPickerSep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn More.
        /// </summary>
        public static string More {
            get {
                return ResourceManager.GetString("More", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Most Recent Treatment Report.
        /// </summary>
        public static string MostRecentTreatmentReport {
            get {
                return ResourceManager.GetString("MostRecentTreatmentReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After you create your patient profile, you will receive individualized medical information related to your personal health situation. Our tools may also help you organize and store the medical information you collected from other sources, generate various reports to help you understand and walk through the complicated diagnostic and treatment processes, and manage your treatment plan and experience..
        /// </summary>
        public static string MyAccess {
            get {
                return ResourceManager.GetString("MyAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NCCN.
        /// </summary>
        public static string NCCN {
            get {
                return ResourceManager.GetString("NCCN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List treatments published in recent months that have not been adopted into standard treatments, but have potential benefits to patients..
        /// </summary>
        public static string NewTreatmentReportLegend {
            get {
                return ResourceManager.GetString("NewTreatmentReportLegend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non-Small Cell Lung Cancer.
        /// </summary>
        public static string NSCLC {
            get {
                return ResourceManager.GetString("NSCLC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OncoLink.
        /// </summary>
        public static string OncoLink {
            get {
                return ResourceManager.GetString("OncoLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to please wait, the online clinic is on the way....
        /// </summary>
        public static string OnlineClinicUnderDevelopment {
            get {
                return ResourceManager.GetString("OnlineClinicUnderDevelopment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online Live Consulting.
        /// </summary>
        public static string OnlineLiveConsulting {
            get {
                return ResourceManager.GetString("OnlineLiveConsulting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources.
        /// </summary>
        public static string OnlineResources {
            get {
                return ResourceManager.GetString("OnlineResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online Tools.
        /// </summary>
        public static string OnlineTools {
            get {
                return ResourceManager.GetString("OnlineTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organize Medical Information.
        /// </summary>
        public static string OrganizeMedicalnformation {
            get {
                return ResourceManager.GetString("OrganizeMedicalnformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Cancer Information Sites.
        /// </summary>
        public static string OtherCancerInformationSites {
            get {
                return ResourceManager.GetString("OtherCancerInformationSites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pancrea Cancer.
        /// </summary>
        public static string PancreaticCancer {
            get {
                return ResourceManager.GetString("PancreaticCancer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age.
        /// </summary>
        public static string PatientAge {
            get {
                return ResourceManager.GetString("PatientAge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancer Type.
        /// </summary>
        public static string PatientCancerType {
            get {
                return ResourceManager.GetString("PatientCancerType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hospital the Diagnosis Made.
        /// </summary>
        public static string PatientDiagnosedFrom {
            get {
                return ResourceManager.GetString("PatientDiagnosedFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month/Year Diagnosed.
        /// </summary>
        public static string PatientDiagnosedOn {
            get {
                return ResourceManager.GetString("PatientDiagnosedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagnosis.
        /// </summary>
        public static string PatientDiagnosis {
            get {
                return ResourceManager.GetString("PatientDiagnosis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ethnic Group.
        /// </summary>
        public static string PatientEthnicGroup {
            get {
                return ResourceManager.GetString("PatientEthnicGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Goals.
        /// </summary>
        public static string PatientGoals {
            get {
                return ResourceManager.GetString("PatientGoals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Concerns.
        /// </summary>
        public static string PatientMainConcerns {
            get {
                return ResourceManager.GetString("PatientMainConcerns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sex.
        /// </summary>
        public static string PatientSex {
            get {
                return ResourceManager.GetString("PatientSex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stage.
        /// </summary>
        public static string PatientStage {
            get {
                return ResourceManager.GetString("PatientStage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal Medical Information Management.
        /// </summary>
        public static string PersonalMedicalInformationManagement {
            get {
                return ResourceManager.GetString("PersonalMedicalInformationManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Month and Year Diagonosed].
        /// </summary>
        public static string PlaceHolderMonthAndYearDiagnosed {
            get {
                return ResourceManager.GetString("PlaceHolderMonthAndYearDiagnosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Name of Disease].
        /// </summary>
        public static string PlaceHolderNameOfDisease {
            get {
                return ResourceManager.GetString("PlaceHolderNameOfDisease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Popular Health Websites In USA.
        /// </summary>
        public static string PopularHealthWebsitesUSA {
            get {
                return ResourceManager.GetString("PopularHealthWebsitesUSA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prepare Hospital Visit.
        /// </summary>
        public static string PrepareForHospitalVisit {
            get {
                return ResourceManager.GetString("PrepareForHospitalVisit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prepare Report For Doctor.
        /// </summary>
        public static string PrepareReportForDoctor {
            get {
                return ResourceManager.GetString("PrepareReportForDoctor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pre-Treatment Evaluation.
        /// </summary>
        public static string PreTreatmentEvaluation {
            get {
                return ResourceManager.GetString("PreTreatmentEvaluation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Policy.
        /// </summary>
        public static string PrivacyPolicy {
            get {
                return ResourceManager.GetString("PrivacyPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procedures commonly used to diagnoze this cancer.
        /// </summary>
        public static string ProceduresForDiagnosis {
            get {
                return ResourceManager.GetString("ProceduresForDiagnosis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procedures used to stage this cancer.
        /// </summary>
        public static string ProceduresOfStaging {
            get {
                return ResourceManager.GetString("ProceduresOfStaging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string ProfileNextPage {
            get {
                return ResourceManager.GetString("ProfileNextPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        public static string ProfilePreviousPage {
            get {
                return ResourceManager.GetString("ProfilePreviousPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 1. Create Patient Profile.
        /// </summary>
        public static string ProfileStep1 {
            get {
                return ResourceManager.GetString("ProfileStep1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 2. Answer Questions About Current Disease.
        /// </summary>
        public static string ProfileStep2 {
            get {
                return ResourceManager.GetString("ProfileStep2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 3. Fill Out Medical History.
        /// </summary>
        public static string ProfileStep3 {
            get {
                return ResourceManager.GetString("ProfileStep3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 4. Upload Medical Records.
        /// </summary>
        public static string ProfileStep4 {
            get {
                return ResourceManager.GetString("ProfileStep4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 5. Confirm Service &amp; Make Payment.
        /// </summary>
        public static string ProfileStep5 {
            get {
                return ResourceManager.GetString("ProfileStep5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagnosis.
        /// </summary>
        public static string ProfileTabDiagnosis {
            get {
                return ResourceManager.GetString("ProfileTabDiagnosis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Family History.
        /// </summary>
        public static string ProfileTabFamilyHistory {
            get {
                return ResourceManager.GetString("ProfileTabFamilyHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make Payment.
        /// </summary>
        public static string ProfileTabMakePayment {
            get {
                return ResourceManager.GetString("ProfileTabMakePayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medical History.
        /// </summary>
        public static string ProfileTabMedicalHistory {
            get {
                return ResourceManager.GetString("ProfileTabMedicalHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overall Health.
        /// </summary>
        public static string ProfileTabOverallHealth {
            get {
                return ResourceManager.GetString("ProfileTabOverallHealth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient.
        /// </summary>
        public static string ProfileTabPatient {
            get {
                return ResourceManager.GetString("ProfileTabPatient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pre-TreatmentEvaluation.
        /// </summary>
        public static string ProfileTabPreTreatmentEvaluation {
            get {
                return ResourceManager.GetString("ProfileTabPreTreatmentEvaluation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procedures Received.
        /// </summary>
        public static string ProfileTabProceduresReceived {
            get {
                return ResourceManager.GetString("ProfileTabProceduresReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required Records.
        /// </summary>
        public static string ProfileTabRequiredRecords {
            get {
                return ResourceManager.GetString("ProfileTabRequiredRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Summary.
        /// </summary>
        public static string ProfileTabServiceSummary {
            get {
                return ResourceManager.GetString("ProfileTabServiceSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Social History.
        /// </summary>
        public static string ProfileTabSocialHistory {
            get {
                return ResourceManager.GetString("ProfileTabSocialHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State of Disease.
        /// </summary>
        public static string ProfileTabStateOfDisease {
            get {
                return ResourceManager.GetString("ProfileTabStateOfDisease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Review.
        /// </summary>
        public static string ProfileTabSystemReview {
            get {
                return ResourceManager.GetString("ProfileTabSystemReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploaded Records.
        /// </summary>
        public static string ProfileTabUploadedRecords {
            get {
                return ResourceManager.GetString("ProfileTabUploadedRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Record.
        /// </summary>
        public static string ProfileTabUploadRecord {
            get {
                return ResourceManager.GetString("ProfileTabUploadRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What does pathological report mean to you.
        /// </summary>
        public static string ReadPathologicalReport {
            get {
                return ResourceManager.GetString("ReadPathologicalReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read Privacy Polict for Creating Patient Profile.
        /// </summary>
        public static string ReadPrivacyPolicy {
            get {
                return ResourceManager.GetString("ReadPrivacyPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our domestic and American medical expert will review patient&apos;s individual diagnostic and treatment situation, answer individual questions and provide a comprehensive treatment report..
        /// </summary>
        public static string ReceiveSecondOpinion {
            get {
                return ResourceManager.GetString("ReceiveSecondOpinion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you would like to come to USA to receive treatment or obtain medicine, we will provide help to communicate with the desired hospital or clinic, translate your patient profile and provide any necessary help, inlcuding  transportation and accomodation..
        /// </summary>
        public static string ReceiveTreatmentFromUSA {
            get {
                return ResourceManager.GetString("ReceiveTreatmentFromUSA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When you want to know a specific disease or health condition, the network can be a good source of information. But you have to judge the reliability and accuracy of this information. First of all you need to know whether the information written and reviewed by professionals. Then you need to know if the evidence is based on evidence or personal opinion or experience. last you have to know if the information is out of date.
        ///Any site offers health-related information should tell you the source of the informa [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ReliableHealthInformation {
            get {
                return ResourceManager.GetString("ReliableHealthInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reviewing Board.
        /// </summary>
        public static string ReviewingBoard {
            get {
                return ResourceManager.GetString("ReviewingBoard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Risks you may have.
        /// </summary>
        public static string RisksYouHave {
            get {
                return ResourceManager.GetString("RisksYouHave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screenings are due.
        /// </summary>
        public static string ScreeningsDue {
            get {
                return ResourceManager.GetString("ScreeningsDue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seeking Second Opinion.
        /// </summary>
        public static string SecondOpinion {
            get {
                return ResourceManager.GetString("SecondOpinion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seek Second Opinion.
        /// </summary>
        public static string SeekSecondOpinion {
            get {
                return ResourceManager.GetString("SeekSecondOpinion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services.
        /// </summary>
        public static string Services {
            get {
                return ResourceManager.GetString("Services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share Patient Conditions.
        /// </summary>
        public static string SharePatientConditions {
            get {
                return ResourceManager.GetString("SharePatientConditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special Services.
        /// </summary>
        public static string SpecialServices {
            get {
                return ResourceManager.GetString("SpecialServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special Topic Report.
        /// </summary>
        public static string SpecialTopicReport {
            get {
                return ResourceManager.GetString("SpecialTopicReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We can provide evidence-based research specific for your individual situation. The information collected from professinal journals contributed by all kind of experts in cancer treatment may help you choose most meaningful decision for you and your family..
        /// </summary>
        public static string SpecialTopicReportLegend {
            get {
                return ResourceManager.GetString("SpecialTopicReportLegend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stage code is required.
        /// </summary>
        public static string StageCodeRequired {
            get {
                return ResourceManager.GetString("StageCodeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard Treatment Report.
        /// </summary>
        public static string StandardTreatmentReport {
            get {
                return ResourceManager.GetString("StandardTreatmentReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profesional summary of treatment options recommended by main authorities in US, Japan and China. The report lists detailed information about how the treatment may affect patient&apos;s survivor and quality of life, including the size and frequency of each treatment and toxic effect, what questions to ask from doctors..
        /// </summary>
        public static string StandardTreatmentReportLegend {
            get {
                return ResourceManager.GetString("StandardTreatmentReportLegend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store Medical Records.
        /// </summary>
        public static string StoreMedicalRecords {
            get {
                return ResourceManager.GetString("StoreMedicalRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supportive Care - improve the quality of life.
        /// </summary>
        public static string SupportiveCare {
            get {
                return ResourceManager.GetString("SupportiveCare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symptoms.
        /// </summary>
        public static string Symptoms {
            get {
                return ResourceManager.GetString("Symptoms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symptoms and signs alerting you.
        /// </summary>
        public static string SymptomsAlertingYou {
            get {
                return ResourceManager.GetString("SymptomsAlertingYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid medical term.
        /// </summary>
        public static string TermRequired {
            get {
                return ResourceManager.GetString("TermRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Risks for Disease.
        /// </summary>
        public static string TestDiseaseRisks {
            get {
                return ResourceManager.GetString("TestDiseaseRisks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tests &amp; Procedures.
        /// </summary>
        public static string TestsAndProcedures {
            get {
                return ResourceManager.GetString("TestsAndProcedures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Your Overall Health.
        /// </summary>
        public static string TestYourOverallHealth {
            get {
                return ResourceManager.GetString("TestYourOverallHealth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools &amp; Helper.
        /// </summary>
        public static string ToolsAndHelper {
            get {
                return ResourceManager.GetString("ToolsAndHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track Medical Spendings.
        /// </summary>
        public static string TrackMedicalSpendings {
            get {
                return ResourceManager.GetString("TrackMedicalSpendings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track Treatment Plan.
        /// </summary>
        public static string TrackTreatmentPlan {
            get {
                return ResourceManager.GetString("TrackTreatmentPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Treatment when cancer progresses.
        /// </summary>
        public static string TreatmentAfterProgress {
            get {
                return ResourceManager.GetString("TreatmentAfterProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Treatment when cancer comes back.
        /// </summary>
        public static string TreatmentAfterRecurrence {
            get {
                return ResourceManager.GetString("TreatmentAfterRecurrence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Treatment Decision Aid.
        /// </summary>
        public static string TreatmentDecisionAid {
            get {
                return ResourceManager.GetString("TreatmentDecisionAid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is the treatment feasible?.
        /// </summary>
        public static string TreatmentFeasibility {
            get {
                return ResourceManager.GetString("TreatmentFeasibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Determine treatment goals.
        /// </summary>
        public static string TreatmentGoals {
            get {
                return ResourceManager.GetString("TreatmentGoals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evidence-basedl Treatment Information Service.
        /// </summary>
        public static string TreatmentInformationService {
            get {
                return ResourceManager.GetString("TreatmentInformationService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introduction.
        /// </summary>
        public static string TreatmentReportIntroduction {
            get {
                return ResourceManager.GetString("TreatmentReportIntroduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Best treatment is the treatment that most likely to yield treatment effects, least likely to cause harms to your body and meets your other expectations such as cost and convenience. To find the best treatment, you need to understand the concepts of evidence-based medicine (EBM). EBM is a new health care model widely implemented in the developed countries in the past twenty years. It is the science of integrating the best available evidence with the doctor’s expertise and patient’s values. Best treatment is  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string TreatmentReportOverview {
            get {
                return ResourceManager.GetString("TreatmentReportOverview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procedures.
        /// </summary>
        public static string TreatmentReportProcedures {
            get {
                return ResourceManager.GetString("TreatmentReportProcedures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample.
        /// </summary>
        public static string TreatmentReportSample {
            get {
                return ResourceManager.GetString("TreatmentReportSample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receive Treatment in USA.
        /// </summary>
        public static string TreatmentServiceInUSA {
            get {
                return ResourceManager.GetString("TreatmentServiceInUSA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seeking Treatment in USA.
        /// </summary>
        public static string TreatmentUSA {
            get {
                return ResourceManager.GetString("TreatmentUSA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Understand cancer stage.
        /// </summary>
        public static string UnderstandCancerStages {
            get {
                return ResourceManager.GetString("UnderstandCancerStages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Under Treatment.
        /// </summary>
        public static string UnderTreatment {
            get {
                return ResourceManager.GetString("UnderTreatment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string Unknow {
            get {
                return ResourceManager.GetString("Unknow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancer Information Authorities in USA.
        /// </summary>
        public static string USACancerInformationAuthorities {
            get {
                return ResourceManager.GetString("USACancerInformationAuthorities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USA Hospital Introduction.
        /// </summary>
        public static string USAHospitalIntroduction {
            get {
                return ResourceManager.GetString("USAHospitalIntroduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USA Online Medical Resources.
        /// </summary>
        public static string USAOnlineMedicalResources {
            get {
                return ResourceManager.GetString("USAOnlineMedicalResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What Is Best Treatment?.
        /// </summary>
        public static string WhatIsBestTreatmentLegend {
            get {
                return ResourceManager.GetString("WhatIsBestTreatmentLegend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is reliable health information.
        /// </summary>
        public static string WhatIsReliableHealthInformation {
            get {
                return ResourceManager.GetString("WhatIsReliableHealthInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When You Should See Doctor?.
        /// </summary>
        public static string WhenSeeDoctor {
            get {
                return ResourceManager.GetString("WhenSeeDoctor", resourceCulture);
            }
        }
    }
}
